// src/views/Home.vue
<template>
  <div class="pt-20 pb-12 min-h-screen bg-[#0f0a1a]">
    <div class="max-w-7xl mx-auto px-4">
      <!-- Header -->
      <div class="mb-12">
        <h1 class="text-4xl font-bold text-[#c4b5fd] mb-2">
          预测市场
        </h1>
        <p class="text-lg text-gray-400">
          参与全球事件预测，聚合集体智慧
        </p>
      </div>

      <!-- Search and Filter -->
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
        <div class="md:col-span-2 relative">
          <input
            v-model="searchTerm"
            type="text"
            placeholder="搜索市场..."
            class="w-full px-4 py-2 bg-[#2a1f3d] border border-[#3d2f52] rounded text-gray-300 placeholder-gray-500 focus:outline-none focus:border-[#a78bfa]"
          />
        </div>
        <div class="flex gap-2">
          <button
            @click="filterStatus = 'all'"
            :class="[
              'flex-1 py-2 px-4 rounded transition-all',
              filterStatus === 'all' ? 'btn-primary' : 'btn-secondary'
            ]"
          >
            全部
          </button>
          <button
            @click="filterStatus = 'trading'"
            :class="[
              'flex-1 py-2 px-4 rounded transition-all',
              filterStatus === 'trading' ? 'btn-primary' : 'btn-secondary'
            ]"
          >
            交易中
          </button>
        </div>
      </div>

      <!-- Generate Test Data Button -->
      <div class="mb-8">
        <button
          @click="generateTestData"
          :disabled="marketStore.loading"
          class="btn-primary"
        >
          {{ marketStore.loading ? '生成中...' : '生成测试数据' }}
        </button>
      </div>

      <!-- Markets Grid -->
      <div v-if="marketStore.loading" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <div v-for="i in 6" :key="i" class="card-dark h-64 animate-pulse"></div>
      </div>
      <div v-else-if="filteredMarkets.length === 0" class="card-dark p-8 text-center">
        <p class="text-gray-400">未找到匹配的市场</p>
      </div>
      <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <router-link
          v-for="market in filteredMarkets"
          :key="market.marketId"
          :to="`/market/${market.marketId}`"
          class="block group"
        >
          <div class="card-dark hover:border-[#a78bfa] transition-all cursor-pointer h-full p-6">
            <div class="flex items-start justify-between gap-2 mb-4">
              <h3 class="text-base font-semibold text-gray-200 line-clamp-2 group-hover:text-[#a78bfa] transition-colors">
                {{ market.question }}
              </h3>
              <span :class="[
                'px-2 py-1 rounded text-xs font-medium whitespace-nowrap',
                getStatusColor(market.status)
              ]">
                {{ getStatusLabel(market.status) }}
              </span>
            </div>
            <p class="text-xs text-gray-500 mb-4">
              {{ formatDate(market.closeTime) }}
            </p>

            <!-- Probability Display -->
            <div class="space-y-3 mb-4">
              <div>
                <div class="flex items-center justify-between mb-1">
                  <div class="flex items-center gap-1 text-sm font-medium text-green-400">
                    ✓ YES
                  </div>
                  <span class="text-sm font-bold text-green-400">
                    {{ (market.impliedProbability?.yes * 100 || 50).toFixed(0) }}%
                  </span>
                </div>
                <div class="w-full bg-[#1a1428] rounded-full h-2">
                  <div
                    class="bg-green-500 h-2 rounded-full transition-all"
                    :style="{ width: `${(market.impliedProbability?.yes || 0.5) * 100}%` }"
                  />
                </div>
              </div>
              <div>
                <div class="flex items-center justify-between mb-1">
                  <div class="flex items-center gap-1 text-sm font-medium text-red-400">
                    ✗ NO
                  </div>
                  <span class="text-sm font-bold text-red-400">
                    {{ (market.impliedProbability?.no * 100 || 50).toFixed(0) }}%
                  </span>
                </div>
                <div class="w-full bg-[#1a1428] rounded-full h-2">
                  <div
                    class="bg-red-500 h-2 rounded-full transition-all"
                    :style="{ width: `${(market.impliedProbability?.no || 0.5) * 100}%` }"
                  />
                </div>
              </div>
            </div>

            <!-- Stats -->
            <div class="flex items-center justify-between text-xs text-gray-500">
              <span>交易量: ${{ market.totalVolume.toLocaleString() }}</span>
              <span>{{ market.transactionCount }} 笔</span>
            </div>
          </div>
        </router-link>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useMarketStore } from '../stores/market'

const marketStore = useMarketStore()
const searchTerm = ref('')
const filterStatus = ref('all')

const filteredMarkets = computed(() => {
  return marketStore.markets.filter((market) => {
    const matchesSearch = market.question
      .toLowerCase()
      .includes(searchTerm.value.toLowerCase())
    const matchesStatus =
      filterStatus.value === 'all' || market.status === filterStatus.value
    return matchesSearch && matchesStatus
  })
})

const getStatusColor = (status) => {
  const colors = {
    'trading': 'bg-blue-900 text-blue-300',
    'closed': 'bg-gray-700 text-gray-300',
    'finalized': 'bg-green-900 text-green-300',
    'invalid': 'bg-red-900 text-red-300'
  }
  return colors[status] || 'bg-gray-700 text-gray-300'
}

const getStatusLabel = (status) => {
  const labels = {
    'trading': '交易中',
    'closed': '已关闭',
    'proposed': '已提议',
    'challenged': '已挑战',
    'finalized': '已完成',
    'invalid': '无效'
  }
  return labels[status] || status
}

const formatDate = (date) => {
  return new Date(date).toLocaleDateString('zh-CN')
}

const generateTestData = async () => {
  await marketStore.generateTestData(10)
}

onMounted(() => {
  marketStore.fetchMarkets()
})
</script>

<style scoped>
</style>

// client/src/pages/Home.tsx
import { useEffect, useState } from "react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { TrendingUp, TrendingDown, Search, Filter } from "lucide-react";
import { Skeleton } from "@/components/ui/skeleton";

interface Market {
  marketId: number;
  question: string;
  status: string;
  marketType: string;
  category: string;
  closeTime: string;
  totalVolume: number;
  transactionCount: number;
  impliedProbability?: {
    yes: number;
    no: number;
  };
}

export default function Home() {
  const [markets, setMarkets] = useState<Market[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");
  const [filterStatus, setFilterStatus] = useState("all");

  useEffect(() => {
    const fetchMarkets = async () => {
      try {
        const response = await fetch("http://localhost:3001/api/markets");
        const data = await response.json();
        if (data.success) {
          setMarkets(data.data);
        }
      } catch (error) {
        console.error("Failed to fetch markets:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchMarkets();
  }, []);

  const filteredMarkets = markets.filter((market) => {
    const matchesSearch = market.question
      .toLowerCase()
      .includes(searchTerm.toLowerCase());
    const matchesStatus =
      filterStatus === "all" || market.status === filterStatus;
    return matchesSearch && matchesStatus;
  });

  const getStatusColor = (status: string) => {
    switch (status) {
      case "trading":
        return "bg-blue-100 text-blue-800";
      case "closed":
        return "bg-gray-100 text-gray-800";
      case "finalized":
        return "bg-green-100 text-green-800";
      case "invalid":
        return "bg-red-100 text-red-800";
      default:
        return "bg-gray-100 text-gray-800";
    }
  };

  const getStatusLabel = (status: string) => {
    switch (status) {
      case "trading":
        return "交易中";
      case "closed":
        return "已关闭";
      case "proposed":
        return "已提议";
      case "challenged":
        return "已挑战";
      case "finalized":
        return "已完成";
      case "invalid":
        return "无效";
      default:
        return status;
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
      <div className="container max-w-7xl mx-auto px-4 py-12">
        {/* Header */}
        <div className="mb-12">
          <h1 className="text-4xl font-bold text-foreground mb-2">
            预测市场
          </h1>
          <p className="text-lg text-muted-foreground">
            参与全球事件预测，聚合集体智慧
          </p>
        </div>

        {/* Search and Filter */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
          <div className="md:col-span-2 relative">
            <Search className="absolute left-3 top-3 w-5 h-5 text-muted-foreground" />
            <Input
              placeholder="搜索市场..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-10"
            />
          </div>
          <div className="flex gap-2">
            <Button
              variant={filterStatus === "all" ? "default" : "outline"}
              onClick={() => setFilterStatus("all")}
              className="flex-1"
            >
              全部
            </Button>
            <Button
              variant={filterStatus === "trading" ? "default" : "outline"}
              onClick={() => setFilterStatus("trading")}
              className="flex-1"
            >
              交易中
            </Button>
          </div>
        </div>

        {/* Markets Grid */}
        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {[...Array(6)].map((_, i) => (
              <Card key={i}>
                <CardHeader>
                  <Skeleton className="h-6 w-full mb-2" />
                  <Skeleton className="h-4 w-3/4" />
                </CardHeader>
                <CardContent>
                  <Skeleton className="h-24 w-full" />
                </CardContent>
              </Card>
            ))}
          </div>
        ) : filteredMarkets.length === 0 ? (
          <Card>
            <CardContent className="pt-8 text-center">
              <p className="text-muted-foreground">未找到匹配的市场</p>
            </CardContent>
          </Card>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredMarkets.map((market) => {
              const yesProb = market.impliedProbability?.yes || 0.5;
              const noProb = market.impliedProbability?.no || 0.5;

              return (
                <Link key={market.marketId} href={`/market/${market.marketId}`}>
                  <a className="block group">
                    <Card className="h-full hover:shadow-lg transition-shadow cursor-pointer">
                      <CardHeader>
                        <div className="flex items-start justify-between gap-2 mb-2">
                          <CardTitle className="text-base line-clamp-2 group-hover:text-primary transition-colors">
                            {market.question}
                          </CardTitle>
                          <Badge className={getStatusColor(market.status)}>
                            {getStatusLabel(market.status)}
                          </Badge>
                        </div>
                        <CardDescription className="text-xs">
                          {new Date(market.closeTime).toLocaleDateString(
                            "zh-CN"
                          )}
                        </CardDescription>
                      </CardHeader>
                      <CardContent>
                        {/* Probability Display */}
                        <div className="space-y-3 mb-4">
                          <div>
                            <div className="flex items-center justify-between mb-1">
                              <div className="flex items-center gap-1 text-sm font-medium">
                                <TrendingUp className="w-4 h-4 text-green-600" />
                                YES
                              </div>
                              <span className="text-sm font-bold text-green-600">
                                {(yesProb * 100).toFixed(0)}%
                              </span>
                            </div>
                            <div className="w-full bg-muted rounded-full h-2">
                              <div
                                className="bg-green-600 h-2 rounded-full transition-all"
                                style={{ width: `${yesProb * 100}%` }}
                              />
                            </div>
                          </div>
                          <div>
                            <div className="flex items-center justify-between mb-1">
                              <div className="flex items-center gap-1 text-sm font-medium">
                                <TrendingDown className="w-4 h-4 text-red-600" />
                                NO
                              </div>
                              <span className="text-sm font-bold text-red-600">
                                {(noProb * 100).toFixed(0)}%
                              </span>
                            </div>
                            <div className="w-full bg-muted rounded-full h-2">
                              <div
                                className="bg-red-600 h-2 rounded-full transition-all"
                                style={{ width: `${noProb * 100}%` }}
                              />
                            </div>
                          </div>
                        </div>

                        {/* Stats */}
                        <div className="flex items-center justify-between text-xs text-muted-foreground">
                          <span>交易量: ${market.totalVolume.toLocaleString()}</span>
                          <span>{market.transactionCount} 笔交易</span>
                        </div>
                      </CardContent>
                    </Card>
                  </a>
                </Link>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
