// client/src/components/Navigation.tsx
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { TrendingUp, Menu, X } from "lucide-react";
import { useState } from "react";

export default function Navigation() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <nav className="fixed top-0 left-0 right-0 z-50 bg-background border-b border-border shadow-sm">
      <div className="container max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
        {/* Logo */}
        <Link href="/">
          <a className="flex items-center gap-2 font-bold text-xl text-primary hover:opacity-80 transition-opacity">
            <TrendingUp className="w-6 h-6" />
            <span>Super Truth</span>
          </a>
        </Link>

        {/* Desktop Navigation */}
        <div className="hidden md:flex items-center gap-6">
          <Link href="/">
            <a className="text-foreground hover:text-primary transition-colors">
              市场
            </a>
          </Link>
          <a href="#" className="text-foreground hover:text-primary transition-colors">
            排行榜
          </a>
          <a href="#" className="text-foreground hover:text-primary transition-colors">
            关于
          </a>
        </div>

        {/* Desktop Actions */}
        <div className="hidden md:flex items-center gap-3">
          <Button variant="outline" size="sm">
            连接钱包
          </Button>
        </div>

        {/* Mobile Menu Button */}
        <button
          className="md:hidden"
          onClick={() => setIsOpen(!isOpen)}
        >
          {isOpen ? (
            <X className="w-6 h-6" />
          ) : (
            <Menu className="w-6 h-6" />
          )}
        </button>
      </div>

      {/* Mobile Navigation */}
      {isOpen && (
        <div className="md:hidden border-t border-border bg-background">
          <div className="container px-4 py-4 flex flex-col gap-4">
            <Link href="/">
              <a className="text-foreground hover:text-primary transition-colors">
                市场
              </a>
            </Link>
            <a href="#" className="text-foreground hover:text-primary transition-colors">
              排行榜
            </a>
            <a href="#" className="text-foreground hover:text-primary transition-colors">
              关于
            </a>
            <Button variant="outline" size="sm" className="w-full">
              连接钱包
            </Button>
          </div>
        </div>
      )}
    </nav>
  );
}

// src/components/Navigation.vue
<template>
  <nav class="fixed top-0 left-0 right-0 z-50 bg-[#1a1428] border-b border-[#3d2f52]">
    <div class="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
      <!-- Logo -->
      <router-link to="/" class="flex items-center gap-2 font-bold text-xl text-[#a78bfa] hover:text-[#c4b5fd] transition-colors">
        <span>🎯 Super Truth</span>
      </router-link>

      <!-- Desktop Navigation -->
      <div class="hidden md:flex items-center gap-6">
        <router-link to="/" class="text-gray-300 hover:text-[#a78bfa] transition-colors">
          市场
        </router-link>
        <a href="#" class="text-gray-300 hover:text-[#a78bfa] transition-colors">
          排行榜
        </a>
        <a href="#" class="text-gray-300 hover:text-[#a78bfa] transition-colors">
          关于
        </a>
      </div>

      <!-- Desktop Actions -->
      <div class="hidden md:flex items-center gap-3">
        <WalletInfo />
        <button v-if="!walletStore.isConnected" @click="handleConnect" class="btn-primary">
          连接钱包
        </button>
        <router-link to="/user" class="text-[#a78bfa] hover:text-[#c4b5fd] transition-colors">
          👤
        </router-link>
      </div>

      <!-- Mobile Menu Button -->
      <button class="md:hidden text-[#a78bfa]" @click="mobileMenuOpen = !mobileMenuOpen">
        <span v-if="!mobileMenuOpen">☰</span>
        <span v-else>✕</span>
      </button>
    </div>

    <!-- Mobile Navigation -->
    <div v-if="mobileMenuOpen" class="md:hidden border-t border-[#3d2f52] bg-[#1a1428]">
      <div class="px-4 py-4 flex flex-col gap-4">
        <router-link to="/" class="text-gray-300 hover:text-[#a78bfa] transition-colors">
          市场
        </router-link>
        <a href="#" class="text-gray-300 hover:text-[#a78bfa] transition-colors">
          排行榜
        </a>
        <a href="#" class="text-gray-300 hover:text-[#a78bfa] transition-colors">
          关于
        </a>
        <button v-if="!walletStore.isConnected" @click="handleConnect" class="btn-primary w-full">
          连接钱包
        </button>
        <div v-else class="flex flex-col gap-2 bg-[#2a1f3d] p-3 rounded border border-[#3d2f52]">
          <p class="text-xs text-gray-400">已连接账户</p>
          <p class="text-sm font-mono text-[#a78bfa] break-all">{{ walletStore.account }}</p>
          <p class="text-xs text-gray-400 mt-2">{{ walletStore.chainName }}</p>
        </div>
        <router-link to="/user" class="text-[#a78bfa] hover:text-[#c4b5fd] transition-colors">
          用户中心
        </router-link>
      </div>
    </div>

    <!-- Wallet Modal -->
    <WalletModal :isOpen="showWalletModal" @close="showWalletModal = false" @connected="handleWalletConnected" />
  </nav>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useWalletStore } from '../stores/wallet'
import WalletModal from './WalletModal.vue'
import WalletInfo from './WalletInfo.vue'

const walletStore = useWalletStore()
const mobileMenuOpen = ref(false)
const showWalletModal = ref(false)

const handleConnect = () => {
  showWalletModal.value = true
}

const handleWalletConnected = () => {
  mobileMenuOpen.value = false
}

onMounted(() => {
  // 检查钱包是否已连接
  walletStore.checkIfWalletIsConnected()
})
</script>

<style scoped>
</style>
